meta_title: "OuiBeat - Propulseur d'expérience digitale"
meta_description: "Concepteur d'éxpériences sociales et connectées dédiées aux plus belles activations de marques"
meta_image: "assets/images/meta/home-meta.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@ouibeat" # indispensable pour les Twitter Cards